services:
  frontend:
    container_name: frontend
    image: fortytwodev/frontend:1.0.0
    networks:
      - proxy-frontend
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${APP_TRAEFIK_HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"

  php-api:
    container_name: php-api
    image: fortytwodev/api-php:1.0.1
    env_file:
      - ./.env

    networks:
      - database-php-api
      - proxy-php
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-api.rule=Host(`${PHP_API_TRAEFIK_HOST}`)"
      - "traefik.http.routers.php-api.entrypoints=websecure"
      - "traefik.http.routers.php-api.tls=true"
      - "traefik.docker.network=proxy-php"

  go-api:
    container_name: go-api
    image: fortytwodev/api-go:1.0.0
    networks:
      - database-go-api
      - proxy-go
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-api.rule=Host(`${GO_API_TRAEFIK_HOST}`)"
      - "traefik.http.routers.go-api.entrypoints=websecure"
      - "traefik.http.routers.go-api.tls=true"
      - "traefik.docker.network=proxy-go"

  database:
    container_name: db
    image: fortytwodev/postgres:1.0.1
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    volumes:
      - 'postgres_data:/var/lib/postgresql'
    networks:
      - database-php-api
      - database-go-api
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  database-php-api:
  database-go-api:
  proxy-php:
    external: true
  proxy-go:
    external: true
  proxy-frontend:
    external: true

volumes:
  postgres_data: